# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication, QMainWindow
from pyqtgraph import PlotWidget
import pyqtgraph
import numpy as np
# import seaborn as sns
import pandas as pd


df = pd.read_csv(r'C:\Users\Khan\OneDrive\Desktop\Dawlance\ODUdata.csv')
df = df.loc[df["DC"] != '328.0\x14' ]
df['Time']=pd.to_datetime(df['Time'])
df=df.astype({"DC":'int',"ODU Ambient Temp.":"float"})

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(902, 585)
        MainWindow.setStyleSheet("*{\n"
        "background-color= #3e3d3c;\n"
        "}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(530, 20, 160, 511))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.plot_selections = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.plot_selections.setContentsMargins(10, 0, 0, 0)
        self.plot_selections.setSpacing(50)
        self.plot_selections.setObjectName("plot_selections")
        self.graph_amps = QtWidgets.QRadioButton(self.verticalLayoutWidget_2)
        self.graph_amps.setObjectName("graph_amps")
        self.plot_selections.addWidget(self.graph_amps)
        self.graph_volt = QtWidgets.QRadioButton(self.verticalLayoutWidget_2)
        self.graph_volt.setObjectName("graph_volt")
        self.plot_selections.addWidget(self.graph_volt)
        self.graph_TC1 = QtWidgets.QRadioButton(self.verticalLayoutWidget_2)
        self.graph_TC1.setObjectName("graph_TC1")
        self.plot_selections.addWidget(self.graph_TC1)
        self.graph_power = QtWidgets.QRadioButton(self.verticalLayoutWidget_2)
        self.graph_power.setObjectName("graph_power")
        self.plot_selections.addWidget(self.graph_power)
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(700, 20, 191, 511))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.selectable_variables = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.selectable_variables.setContentsMargins(10, 0, 0, 0)
        self.selectable_variables.setSpacing(50)
        self.selectable_variables.setObjectName("selectable_variables")
        self.select_amps = QtWidgets.QCheckBox(self.verticalLayoutWidget_3)
        self.select_amps.setObjectName("select_amps")
        self.selectable_variables.addWidget(self.select_amps)
        self.select_volt = QtWidgets.QCheckBox(self.verticalLayoutWidget_3)
        self.select_volt.setObjectName("select_volt")
        self.selectable_variables.addWidget(self.select_volt)
        self.select_tc1 = QtWidgets.QCheckBox(self.verticalLayoutWidget_3)
        self.select_tc1.setObjectName("select_tc1")
        self.selectable_variables.addWidget(self.select_tc1)
        self.select_power = QtWidgets.QCheckBox(self.verticalLayoutWidget_3)
        self.select_power.setObjectName("select_power")
        self.selectable_variables.addWidget(self.select_power)
        self.move_across_graph = QtWidgets.QScrollBar(self.centralwidget)
        self.move_across_graph.setGeometry(QtCore.QRect(10, 510, 501, 16))
        self.move_across_graph.setOrientation(QtCore.Qt.Horizontal)
        self.move_across_graph.setObjectName("move_across_graph")
        self.zoomer = QtWidgets.QSlider(self.centralwidget)
        self.zoomer.setGeometry(QtCore.QRect(510, 140, 22, 160))
        self.zoomer.setOrientation(QtCore.Qt.Vertical)
        self.zoomer.setObjectName("zoomer")
        self.graph.setGeometry(QtCore.QRect(10, 30, 501, 511))
        self.graph.setObjectName("graph")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 902, 21))
        self.menuBar.setObjectName("menuBar")
        self.menuAdd_calculated_graph = QtWidgets.QMenu(self.menuBar)
        self.menuAdd_calculated_graph.setObjectName("menuAdd_calculated_graph")
        self.menucalculate_description = QtWidgets.QMenu(self.menuBar)
        self.menucalculate_description.setObjectName("menucalculate_description")
        MainWindow.setMenuBar(self.menuBar)
        self.menuBar.addAction(self.menuAdd_calculated_graph.menuAction())
        self.menuBar.addAction(self.menucalculate_description.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.graph_amps.setText(_translate("MainWindow", "CURRENT (A)"))
        self.graph_volt.setText(_translate("MainWindow", "VOLTAGE (V)"))
        self.graph_TC1.setText(_translate("MainWindow", "TC1"))
        self.graph_power.setText(_translate("MainWindow", "POWER (P)"))
        self.select_amps.setText(_translate("MainWindow", "CURRENT (A)"))
        self.select_volt.setText(_translate("MainWindow", "VOLTAGE (V)"))
        self.select_tc1.setText(_translate("MainWindow", "TC1"))
        self.select_power.setText(_translate("MainWindow", "POWER (P)"))
        self.menuAdd_calculated_graph.setTitle(_translate("MainWindow", "Add calculated graph"))
        self.menucalculate_description.setTitle(_translate("MainWindow", "calculate description"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
